### ISSUE TITLE
apple m1?

### ISSUE THREAD

**Issue by iamcos** [declare-lab/tango#12]
Error message ive got:tango/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 221, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by iamcos** [comment]
Did the following: 
tango = Tango("declare-lab/tango", "mps")

Current error: 
/venv/lib/python3.10/site-packages/transformers/models/t5/modeling_t5.py", line 414, in _relative_position_bucket
    relative_position = torch.abs(relative_position)
TypeError: Operation 'abs_out_mps()' does not support input type 'int64' in MPS backend.

**Comment by iamcos** [comment]
After installing latest nightly pytorch build the problem went away, now its generating.
